### ISSUE TITLE
Read the author guidelines

### ISSUE THREAD

**Issue by vasishth** [vasishth/SchoknechtVasishthInterference#36]
"You are required to provide a concise and factual abstract which does not exceed 250 words. "

The abstract is 388 words right now.

Please check that you meet the guidelines for authors otherwise you now risk throwing this into another round of reviews.

**Comment by PSchoknecht** [comment]
Shortened abstract (243 words):

Cue-based retrieval accounts of sentence processing postulate that at a verb, retrieval cues are generated to complete a dependency with the verb’s argument(s); for example, the dependency between the subject and the verb must be completed. If these retrieval cues match with not only the subject but also with those on other nouns in the sentence, then processing difficulty arises at the verb. This difficulty in identifying the correct dependent is called similarity-based interference. We present large-sample self-paced reading and event-related potentials experiments using a well-established design to investigate interference due to syntactic and semantic cues in German. In this design, the syntactic cue {+subject} and the semantic cue {+animate} are manipulated. Bayes factors analyses showed evidence for a semantic interference effect in both experiments. Surprisingly, Bayes factors provided evidence against interference due to the syntactic cue {+grammatical subject} in this particular design in both experiments. This finding contradicts the predictions of the standard implementations of cue-based retrieval theory, which (implicitly) assume that both syntactic and semantic cues play an equal role in retrieval. We show through computational modeling that cue-based retrieval will also shows no syntactic interference in the present design if the parser is assumed to keep track of which clause the subject occurs in. Thus, if syntactic retrieval cues include hierarchical syntactic information (is the noun in the same clause as the verb?), the predictions of the cue-based retrieval model would be consistent with the observed patterns in our data.
