### ISSUE TITLE
Confusing text in response letter

### ISSUE THREAD

**Issue by vasishth** [vasishth/SchoknechtVasishthInterference#40]
You wrote: 

> We do not share the reviewer’s interpretation that the effects in the later regions are not meaningful. We use the pre-critical reading times as a proxy to investigate the effect of encoding interference caused by the distractor. To emphasize this we have renamed the former section “Pre-critical effects” to “Reading times difference prior to retrieval”. We have revised the beginning of the Discussion on page 30 accordingly

There are two problems here. First, the reviewer didn't say the effects in later regions were not meaningful, she said they were not interpretable. I would agree with that. Second, if you say you don't agree with the reviewer, you have to explain why. Instead, the next sentence goes on to another topic, namely the effect at the pre-critical region. The only way i can make sense of this is that the pre-critical region is supposed to include the pre-critical region. 

In any case, I think the reviewer's point is right, that we can't unpack what happens at the moment of retrieval. I think that is whay she intends here. 

This paragraph should be written more clearly and i would actually not disagree with the reviewer, I would agree with her. Maybe we need to talk about this in person so you can explain what I am missing here.

**Comment by PSchoknecht** [comment]
I guess the confusion stems from different interpretations of what "later regions" means.

The reviewer wrote:
"However, this comes after more than 10 full pages (pp. 25-37) of 
1. **discussion on the reaction times (RTs) in the critical and pre-critical regions, which would lead any reader to believe these findings are meaningful**. If, as the authors now realize, the effect emerges much earlier, this entire discussion is misleading:
2.  the SPR **results after the distractor region are simply uninterpretable**."

In (1), they imply that the pre-critical results are not meaningful. In (2), they say that all RTs after the distractor are uninterpretable. Since we said from the very begining that we cannot interpret the RTs at the distractors because they are different words, the conclusion would be that we cannot interpret any of our SPR results.  In my reply, I wanted to explain/ justify why it makes sense to interpret the RTs in the pre-critical region.

Do you agree with that argumentation?

**Comment by PSchoknecht** [comment]
I revised this response and uploaded the revised files.

**Comment by vasishth** [comment]
I can't proceed with edits until I understand what this sentence and paragraph is trying to respond to.

**Comment by PSchoknecht** [comment]
If you think this defence is unnecessary, I'm ok with dropping it. I felt that it was necessary because the reviewer was opposed to interpreting the SPR data at all (quote from comment R2.1: "the SPR results after the distractor region are simply uninterpretable").

**Comment by vasishth** [comment]
but why the discussion about *semantic* interference in particular?

**Comment by PSchoknecht** [comment]
The encoding interference was due to semantic similarity. I just added that one word (semantic) in that one sentence to restate that.  If it's confusing, you can delete it.

**Comment by vasishth** [comment]
ok. the sudden shift to semantic interfernce is very confusing.
